### ISSUE TITLE
no sound from latest DMXmk2 and CR78mk2

### ISSUE THREAD

**Issue by davephillips** [JerrySievert/DrumKit#5] opened 2018-10-28 12:27 UTC
Fedora 23 Linux
Rack 0.6.2b

Hi Jerry ! The subject says it all. I've tried every input combination I could think of but I'm getting no audio from those two modules. The original DMX and CR78 modules work fine. Any suggestions ?

**Comment by JerrySievert** [comment] 2018-10-29 21:34
what were you using to drive them?

the biggest differences on these two modules is that they require v/oct to select the instrument, and gate to drive it.

in the mean time, I'll try to reproduce, and put out a new release.

interested in taking and sharing a survey? https://www.surveymonkey.com/r/3BXT2WC

**Comment by JerrySievert** [comment] 2018-10-29 21:49
huh. looks like I swapped v/oct and gate - oops, entirely on me.  I'll see what I can do to get a new release out asap, or if you want to build yourself while it goes through the vcv plugin release process, give me about 5 minutes to get some updates committed and pushed.

**Closed as completed** 2018-10-29 21:56 UTC

**Comment by davephillips** [comment] 2018-10-29 23:47
Hi Jerry ! Thanks for the quick repair, the modules are working again. However, I'm getting some unusual range response. The DMXmk2 module triggers from C#4 through C5, while the CR87mk2 triggers from C#4 through G4, and both modules produce an audible click on the sounds at C#4. Just thought you'd want to know. :)

**Comment by davephillips** [comment] 2018-10-29 23:50
The test suite. Tested with trigger and gate modes.

![drumkittest](https://user-images.githubusercontent.com/7815938/47686889-df7de980-dbb3-11e8-80af-986931275c88.png)

**Comment by JerrySievert** [comment] 2018-10-30 20:02
I'm able to get an audible click from dmx mk2 on c5, but as far as c#4, the sample is a stuttered high hat, is that what you're hearing?  if not, can you provide a quick recording of it?

not hearing a click that isn't part of the drive on crx either.

**Comment by davephillips** [comment] 2018-11-06 12:42
Hey Jerry, sorry for the delayed reply. Thanks, everything is working okay, I'm not sure what I was or wasn't doing that caused problems here. All good now, and thanks again for the excellent plugins.
